import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import './globals.css'

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['500', '700'], // The design system uses Medium (Body) and Bold (Headings)
  variable: '--font-league-spartan',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${leagueSpartan.variable} h-full antialiased`}>
      {/* We apply the global background (neutral-100 in light mode, dark-bg in dark mode)
    and the global text colors.
  */}
      <body className="text-dark-text dark:bg-dark-bg flex min-h-full flex-col bg-neutral-400 font-sans transition-colors duration-200 dark:text-white">
        {children}
      </body>
    </html>
  )
}
